name: Run unit tests and publish samples

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: npm install and test
      run: |
        npm ci
        npm run test:unit
    - name: release samples
      run: |
        npm ci
        npm run release:samples
      env:
        CI: true
