name: Run unit tests and publish samples

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: npm install and test
      run: |
        npm ci
        npm run test:unit
    - name: Release Samples
      uses: crazy-max/ghaction-github-pages@v1.4.0
      with:
        build_dir: dist
      env:
        CI: true
