name: Run unit tests and publish samples

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: npm install and test
      run: |
        npm ci
        npm run test:unit
    - name: build samples
      run: |
        npx vue-cli-service build
    - name: configure git credentials
      run: |
        git config user.name "Karol Etrych"
        git config user.email "karol.etrych@gmail.com"
    - name: release samples to ghpages
      run: |
        npx gh-pages -d dist
      env:
        CI: true
